framework:
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        default_redis_provider: redis://localhost

        pools:
            cache.app:
                adapter: cache.adapter.filesystem
            cache.system:
                adapter: cache.adapter.system
