# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true

    # Trusted hosts patterns
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    # Session configuration
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # PHP errors
    php_errors:
        log: true

    # Cache
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system

    # Rate limiter
    rate_limiter:
        anonymous:
            policy: 'sliding_window'
            limit: 100
            interval: '5 minutes'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
